id: P000300
initial_creation_type: ocr
created_at: 10/03/2020
last_modified_at: 26/11/2021
source_metadata:
  id: bdr:W1PD95807
  title: འདུལ་བ་བདུད་རྩིའི་ཉིང་ཁུ
  author: ''
  volumes:
    1992db26889047588faf7127cbaac3bc:
      image_group_id: I1PD95832
      title: Volume 1 of 'dul ba bdud rts'i nying khu
      volume_number: 1
      total_pages: 390
      base_file: v001.txt
